version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
    - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - './docker/nginx/conf.d:/etc/nginx/conf.d'
    - './src:/var/www/html'

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: kto-ya123